### ISSUE TITLE
add common pitfall: using action

### ISSUE THREAD

**Issue by rosshinkley** [rosshinkley/nightmare-examples#3]
Wrapping actions inside of `.action()` might not behave as one would expect.  Example:

``` js
Nightmare.action('example', function(done){
    this.wait('body').screenshot('someScreenshot.png').wait(1000);
    done();
});
```

**Comment by Mr0grog** [comment]
Oh, oof, I hadn’t thought of using `action` this way, but it would be nice if you could.

I think the short explanation here is that it’s just unsafe/doesn’t work to queue anything from inside an action—the only things you can do are `this.evaluate_now` or emit messages on `this.child`. That needs more explanation, though—until you’ve dug through nightmare’s internals, those words don’t all make a lot of sense.

**Comment by rosshinkley** [comment]
Well, you _can_ use it this way through leveraging `.then()`, but it might (probably does) have some side effects.  Consider:

``` js
Nightmare.action('example', function(done){
    this.wait('body').screenshot('someScreenshot.png').wait(1000).then(done);
});
```

This "works" as the queue will tack on the `.example()` actions, execute the stack as it exists in that moment, then start anew with whatever is after `.example()`.

In general, though, I think the advice I'd give is "use `.use()`".  That seems to be what `.use()` is really intended for - wrapping several common actions in a single, easy-to-reuse package.  Unfortunately, the current documentation for `.use()` is lacking.

Thoughts on adding something about `.use()`?  Not exactly sure where it fits at the moment, but I think it'd be a worthwhile addition.

**Comment by Mr0grog** [comment]
Ah, that would work! Definitely has lots of caveats and gotchas, though (e.g. there might be other things on the queue before the user starts adding stuff inside their action).

> Thoughts on adding something about .use()?

It certainly seems like this is exactly the use-case `use` is designed for. It probably deserves it’s own section—maybe “making re-usable actions with use()” or something. Or just “extending Nightmare,” which covers both `action` and `use` and when to use each.

The examples Nighmare’s readme links to are pretty good examples, but they definitely lack for a basic description of exactly what they’re doing and how. They’re also kind of specific to to a particular site that not a lot of people know, so that’s not especially great. Maybe bundling the yahoo example into a function would be a good example, allowing someone to write code like:

``` js
nightmare
  .use(yahooTopResult('github nightmare'))
  .then(url => console.log(url));
```
